size_t get_pointer_size();
void using_pointers();
void pointer_arith();
void pointer_abuse();
void generic_pointers();
char probe_byte();
size_t passed_array_size(int array[]);
int* bad_array_return();
int* array_return(int size);
void passed_array_demo();
size_t passed_array_pointer(int (*ptri)[]);